### ISSUE TITLE
Ar Watch

### ISSUE THREAD

**Issue by genia1991** [kadiraydinli/Ar-Watch#1]
hi. I have some trobles with an app for Ar Watch. The problem is that when I start apk file and click connect to my bluetooth module. Your app takes off :(
Plx could you help me? What am I doing wrong?

**Comment by kadiraydinli** [comment]
@genia1991  Hello, I'm back late, sorry. I fixed the Android app crashing problem and made some edits. I am closing this issue for now, you can turn it back on if you have problems again.
